
export const fullMockArticleListData = [
    {
        "article_id": 97,
        "article_version_id": 31,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-02",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 1,
        "rating": 5,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "some title"
    },
    {
        "article_id": 96,
        "article_version_id": 26,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-01",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 2,
        "rating": 3,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "another title"
    },
    {
        "article_id": 95,
        "article_version_id": 30,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-02",
        "moderator_id": null,
        "rates_cnt": 0,
        "rating": 0,
        "status": "on_review",
        "text": "something edited 3",
        "title": "new"
    },
    {
        "article_id": 94,
        "article_version_id": 22,
        "author_id": 63,
        "author_name": "r",
        "last_change": "2023-04-24",
        "moderator_id": null,
        "rates_cnt": 0,
        "rating": 0,
        "status": "on_review",
        "text": "23r2rfsvfvb",
        "title": "title 3"
    },
    {
        "article_id": 93,
        "article_version_id": 21,
        "author_id": 62,
        "author_name": "222",
        "last_change": "2023-04-22",
        "moderator_id": 62,
        "moderator_name": "222",
        "rates_cnt": 1,
        "rating": 3,
        "status": "published",
        "text": "fvdbf  cvb cv v bcvb v",
        "title": "react title"
    },
    {
        "article_id": 92,
        "article_version_id": 17,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-04-22",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 1,
        "rating": 5,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "iii"
    },
    {
        "article_id": 91,
        "article_version_id": 14,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-04-22",
        "moderator_id": 62,
        "moderator_name": "222",
        "rates_cnt": 3,
        "rating": 3,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "test"
    },
    {
        "article_id": 89,
        "article_version_id": 13,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-04-03",
        "moderator_id": null,
        "rates_cnt": 0,
        "rating": 0,
        "status": "on_review",
        "text": "First paragraph of the potential article",
        "title": "title"
    },
    {
        "article_id": 6,
        "article_version_id": 8,
        "author_id": 3,
        "author_name": "Aang",
        "last_change": "2020-08-08",
        "moderator_id": 6,
        "moderator_name": "Thomas",
        "rates_cnt": 8,
        "rating": 3,
        "status": "published",
        "text": " nisi ut aliquid ex ea comm",
        "title": "Very-very interesting title6"
    },
    {
        "article_id": 5,
        "article_version_id": 7,
        "author_id": 3,
        "author_name": "Aang",
        "last_change": "2020-07-08",
        "moderator_id": 6,
        "moderator_name": "Thomas",
        "rates_cnt": 20,
        "rating": 3.15001,
        "status": "published",
        "text": "Sed ut perspiciat",
        "title": "Very-very interesting title5"
    },
    {
        "article_id": 4,
        "article_version_id": 6,
        "author_id": 3,
        "author_name": "Aang",
        "last_change": "2020-06-08",
        "moderator_id": null,
        "rates_cnt": 8,
        "rating": 3,
        "status": "on_review",
        "text": "in voluptate velit esse cillum",
        "title": "Very-very interesting title4"
    },
    {
        "article_id": 3,
        "article_version_id": 9,
        "author_id": 3,
        "author_name": "Aang",
        "last_change": "2020-10-22",
        "moderator_id": 6,
        "moderator_name": "Thomas",
        "rates_cnt": 8,
        "rating": 3,
        "status": "published",
        "text": "ctetur, adipisci velit, se",
        "title": "Very-very interesting title7"
    },
    {
        "article_id": 2,
        "article_version_id": 4,
        "author_id": 3,
        "author_name": "Aang",
        "last_change": "2023-04-30",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 74,
        "rating": 3.31081,
        "status": "published",
        "text": "incididunt ut labore et dolore magna",
        "title": "Very-very interesting title2"
    },
    {
        "article_id": 1,
        "article_version_id": 19,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-04-04",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 78,
        "rating": 3.03844,
        "status": "published",
        "text": "Aded new version",
        "title": "Aded new version"
    }
];


export const mockArticleListData = [
    {
        "article_id": 97,
        "article_version_id": 31,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-02",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 1,
        "rating": 5,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "some title"
    },
    {
        "article_id": 96,
        "article_version_id": 26,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-01",
        "moderator_id": 60,
        "moderator_name": "user",
        "rates_cnt": 2,
        "rating": 3,
        "status": "published",
        "text": "First paragraph of the potential article",
        "title": "another title"
    },
    {
        "article_id": 95,
        "article_version_id": 30,
        "author_id": 60,
        "author_name": "user",
        "last_change": "2023-05-02",
        "moderator_id": null,
        "rates_cnt": 0,
        "rating": 0,
        "status": "on_review",
        "text": "something edited 3",
        "title": "new"
    }
];

export const mockArticleData = {
    "article_id": 95,
    "article_version_id": 30,
    "author_id": 60,
    "author_name": "user",
    "last_change": "2023-05-02",
    "moderator_id": null,
    "rates_cnt": 0,
    "rating": 0,
    "status": "on_review",
    "text": "something edited 3",
    "title": "new"
};

export const mockApprovedArticleData = {
    "article_id":95,
    "article_version_id":30,
    "author_id":60,
    "author_name":"user",
    "last_change":"2023-05-29",
    "moderator_id":60,
    "moderator_name":"user",
    "rates_cnt":3,
    "rating":3.0,
    "status":"published",
    "text":"something edited 3",
    "title":"new"}
